using Microsoft.EntityFrameworkCore;

namespace Core.Data;

public static class GenerateAiDbContextFactory
{
    public const string ConnectionStringEnvironmentName = "GENERATEAI_DB_CONNECTION";

    public static GenerateAiDbContext? CreateFromEnvironment(bool ensureCreated = true)
    {
        string? connectionString = Environment.GetEnvironmentVariable(ConnectionStringEnvironmentName);
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return null;
        }

        DbContextOptions<GenerateAiDbContext> options = new DbContextOptionsBuilder<GenerateAiDbContext>()
            .UseNpgsql(connectionString)
            .Options;

        GenerateAiDbContext dbContext = new(options);

        if (ensureCreated)
        {
            EnsureGenerateAiSchema(dbContext);
        }

        return dbContext;
    }

    public static void EnsureGenerateAiSchema(GenerateAiDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw($"""CREATE SCHEMA IF NOT EXISTS "{GenerateAiDbContext.DatabaseSchemaName}";""");
        dbContext.Database.ExecuteSqlRaw($"""
                                         CREATE TABLE IF NOT EXISTS "{GenerateAiDbContext.DatabaseSchemaName}"."Models" (
                                             "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                             "ModelName" character varying(64) NOT NULL,
                                             CONSTRAINT "PK_Models" PRIMARY KEY ("Id")
                                         );
                                         """);

        dbContext.Database.ExecuteSqlRaw($"""
                                         CREATE TABLE IF NOT EXISTS "{GenerateAiDbContext.DatabaseSchemaName}"."Contents" (
                                             "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                                             "Role" character varying(32) NOT NULL,
                                             "Message" text NOT NULL,
                                             "Hash" character varying(128) NULL,
                                             "ModelId" integer NOT NULL,
                                             "CreatedAt" timestamp with time zone NOT NULL,
                                             CONSTRAINT "PK_Contents" PRIMARY KEY ("Id"),
                                             CONSTRAINT "FK_Contents_Models_ModelId" FOREIGN KEY ("ModelId")
                                                 REFERENCES "{GenerateAiDbContext.DatabaseSchemaName}"."Models" ("Id")
                                                 ON DELETE RESTRICT
                                         );
                                         """);

        dbContext.Database.ExecuteSqlRaw($"""
                                         CREATE TABLE IF NOT EXISTS "{GenerateAiDbContext.DatabaseSchemaName}"."Conversations" (
                                             "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                                             "ParentConversationId" bigint NULL,
                                             "InputContentId" bigint NOT NULL,
                                             "OutputContentId" bigint NOT NULL,
                                             "CreatedAt" timestamp with time zone NOT NULL,
                                             CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
                                             CONSTRAINT "FK_Conversations_Conversations_ParentConversationId" FOREIGN KEY ("ParentConversationId")
                                                 REFERENCES "{GenerateAiDbContext.DatabaseSchemaName}"."Conversations" ("Id")
                                                 ON DELETE RESTRICT,
                                             CONSTRAINT "FK_Conversations_Contents_InputContentId" FOREIGN KEY ("InputContentId")
                                                 REFERENCES "{GenerateAiDbContext.DatabaseSchemaName}"."Contents" ("Id")
                                                 ON DELETE RESTRICT,
                                             CONSTRAINT "FK_Conversations_Contents_OutputContentId" FOREIGN KEY ("OutputContentId")
                                                 REFERENCES "{GenerateAiDbContext.DatabaseSchemaName}"."Contents" ("Id")
                                                 ON DELETE RESTRICT
                                         );
                                         """);

        dbContext.Database.ExecuteSqlRaw($"""
                                         CREATE TABLE IF NOT EXISTS "{GenerateAiDbContext.DatabaseSchemaName}"."OutputCaches" (
                                             "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                                             "OutputContentId" bigint NOT NULL,
                                             "ModelId" integer NOT NULL,
                                             "Provider" character varying(32) NOT NULL,
                                             "CacheKey" character varying(256) NOT NULL,
                                             "CacheType" character varying(64) NOT NULL,
                                             "SequenceIndex" integer NULL,
                                             "CreatedAt" timestamp with time zone NOT NULL,
                                             "ExpiredAt" timestamp with time zone NULL,
                                             CONSTRAINT "PK_OutputCaches" PRIMARY KEY ("Id"),
                                             CONSTRAINT "FK_OutputCaches_Contents_OutputContentId" FOREIGN KEY ("OutputContentId")
                                                 REFERENCES "{GenerateAiDbContext.DatabaseSchemaName}"."Contents" ("Id")
                                                 ON DELETE CASCADE,
                                             CONSTRAINT "FK_OutputCaches_Models_ModelId" FOREIGN KEY ("ModelId")
                                                 REFERENCES "{GenerateAiDbContext.DatabaseSchemaName}"."Models" ("Id")
                                                 ON DELETE RESTRICT
                                         );
                                         """);

        EnsureIndexes(dbContext);
        SeedModels(dbContext);
    }

    private static void EnsureIndexes(GenerateAiDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw($"""CREATE UNIQUE INDEX IF NOT EXISTS "IX_Models_ModelName" ON "{GenerateAiDbContext.DatabaseSchemaName}"."Models" ("ModelName");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_Contents_Hash" ON "{GenerateAiDbContext.DatabaseSchemaName}"."Contents" ("Hash");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_Contents_ModelId" ON "{GenerateAiDbContext.DatabaseSchemaName}"."Contents" ("ModelId");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_Conversations_ParentConversationId" ON "{GenerateAiDbContext.DatabaseSchemaName}"."Conversations" ("ParentConversationId");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_Conversations_InputContentId" ON "{GenerateAiDbContext.DatabaseSchemaName}"."Conversations" ("InputContentId");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_Conversations_OutputContentId" ON "{GenerateAiDbContext.DatabaseSchemaName}"."Conversations" ("OutputContentId");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutputCaches_CacheKey" ON "{GenerateAiDbContext.DatabaseSchemaName}"."OutputCaches" ("CacheKey");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_OutputCaches_ModelId" ON "{GenerateAiDbContext.DatabaseSchemaName}"."OutputCaches" ("ModelId");""");
        dbContext.Database.ExecuteSqlRaw($"""CREATE INDEX IF NOT EXISTS "IX_OutputCaches_OutputContentId_Provider" ON "{GenerateAiDbContext.DatabaseSchemaName}"."OutputCaches" ("OutputContentId", "Provider");""");
    }

    private static void SeedModels(GenerateAiDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw($"""
                                         INSERT INTO "{GenerateAiDbContext.DatabaseSchemaName}"."Models" ("Id", "ModelName")
                                         VALUES
                                             (1, 'gpt'),
                                             (2, 'gemini'),
                                             (3, 'claude'),
                                             (4, 'grok'),
                                             (5, 'deepseek')
                                         ON CONFLICT ("Id") DO UPDATE
                                         SET "ModelName" = EXCLUDED."ModelName";
                                         """);
    }
}
